src/main/java/com/poultry/jp/model/Batch.java
package com.poultry.jp.model;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;



@Entity
@NamedQueries({
	@NamedQuery(name= Batch.GETBATCHREPORT,query="SELECT new com.poultry.jp.report.BatchReport(b.batchId,b.date,b.quantity,b.chickPrice,b.purchaseOrderValue,b.actualOrderValue,b.discount,b.waxingTotal,b.oneChickWaxingCost,b.waxingStatus,b.supplier,b.paymentRequest,b.isApproved) FROM Batch b ")
	
})
//@JsonIgnoreProperties(value = { "farmer" ,"fieldOfficer","supplyBatch"})
@JsonIdentityInfo(generator=ObjectIdGenerators.IntSequenceGenerator.class, property="@task")
public class Batch {

	public static final String GETBATCHREPORT = "findBatchReportByFieldOfficer";
	public static final String GET_BATCHDATESANDID = "getBatchDates&Ids";
	public static final String FIND_BATCHBYID ="findBatchById";

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long batchId;
	@NotNull
	private int quantity;
	@NotNull
	private double chickPrice;
	@NotNull
	private double purchaseOrderValue;
	@NotNull
	private double actualOrderValue;
	
	private double discount;
	
	private double waxingTotal;
	private double oneChickWaxingCost;
	private boolean waxingStatus;
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@Temporal(TemporalType.DATE)
	@NotNull
	private Date date;
	
	@ManyToOne
	private Supplier supplier;
	
	private int issuedAmount;
	
	
	@OneToOne(cascade={CascadeType.MERGE , CascadeType.PERSIST})
	@JoinColumn(name = "paymentRequest_id")
	@Valid
	private PaymentRequest paymentRequest;
	
	private boolean isDeleted;
	private Date created;
	private Date updated;
	
	private boolean isApproved;

	
	public PaymentRequest getPaymentRequest() {
		return paymentRequest;
	}

	public void setPaymentRequest(PaymentRequest paymentRequest) {
		this.paymentRequest = paymentRequest;
	}
	
	public double getActualOrderValue() {
		return actualOrderValue;
	};
	
	public double getChickPrice() {
		return chickPrice;
	}

	public double getDiscount() {
		return discount;
	}

	public double getOneChickWaxingCost() {
		return oneChickWaxingCost;
	}

	public double getPurchaseOrderValue() {
		return purchaseOrderValue;
	}

	public boolean getWaxingStatus() {
		return waxingStatus;
	}

	public double getWaxingTotal() {
		return waxingTotal;
	}

	public void setActualOrderValue(double actualOrderValue) {
		this.actualOrderValue = actualOrderValue;
	}

	
	public void setChickPrice(double chickPrice) {
		this.chickPrice = chickPrice;
	}

	public void setDiscount(double discount) {
		this.discount = discount;
	}
	
	public void setOneChickWaxingCost(double oneChickWaxingCost) {
		this.oneChickWaxingCost = oneChickWaxingCost;
	}

	public void setPurchaseOrderValue(double purchaseOrderValue) {
		this.purchaseOrderValue = purchaseOrderValue;
	}
	
	public void setWaxingStatus(boolean waxingStatus) {
		this.waxingStatus = waxingStatus;
	}

	public void setWaxingTotal(double waxingTotal) {
		this.waxingTotal = waxingTotal;
	}

	
	public Long getBatchId() {
		return batchId;
	}
	 
	public int getQuantity() {
		return quantity;
	}

	public void setBatchId(Long batchId) {
		this.batchId = batchId;
	}

	
	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	
	public Supplier getSupplier() {
		return supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}
	
	@PrePersist
	protected void onCreate() {
		created = new Date();
	}

	@PreUpdate
	protected void onUpdate() {
		updated = new Date();
	}

	public boolean isDeleted() {
		return isDeleted;
	}

	public void setDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public int getIssuedAmount() {
		return issuedAmount;
	}

	public void setIssuedAmount(int issuedAmount) {
		this.issuedAmount = issuedAmount;
	}

	public boolean isApproved() {
		return isApproved;
	}

	public void setApproved(boolean isApproved) {
		this.isApproved = isApproved;
	}
}

src/main/java/com/poultry/jp/controller/LoginController.java
package com.poultry.jp.controller;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Controller
public class LoginController {
	
	@RequestMapping(value= "/login", method = RequestMethod.GET)
	public String login(Model model){
		 
		return "login";
	}

}

src/main/webapp/WEB-INF/jsp/addBatchFeed.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<%@include file="layouts/header.jsp"%>
<title>Add Batch Feed - JP Poultry</title>



<script type="text/javascript" src="../resources/js/jquery.min.js"></script>
<script>
jQuery(function($) {
    $('#inputQuantity, #inputUnitPrice').on('keyup', function() {
    var unitPrice = document.getElementById('inputUnitPrice').value;
    var quantity = document.getElementById('inputQuantity').value;
    var amount = parseFloat(unitPrice) * parseFloat(quantity);
    
    if (!isNaN(amount)) {
       document.getElementById('inputAmount').value = amount.toFixed(2);
    }
    
    });
});
</script>

<script type="text/javascript">

$(document).ready(function() {
    $('#inputFeed').on('change', function() {
    //  alert( this.value ); // or $(this).val()
      
      var id = this.value;
      
      console.log(id);
      
      $.ajax({
    	  url: './getFeedObject.json?fid='+id+'',
    	  success: function(data){
    		  console.log(data);
    		  $('#inputUnitPrice').val(data.price);
    		  var unitPrice = document.getElementById('inputUnitPrice').value;
    		  var quantity = document.getElementById('inputQuantity').value;
    		  var amount = parseFloat(unitPrice) * parseFloat(quantity);
    		    
    		  if (!isNaN(amount)) {
    		     document.getElementById('inputAmount').value = amount.toFixed(2);
    		  }
    		  
    	  }
    	});
      return false;
    });
});
</script>
<script>
$(document).ready(function() {  
    $('#inputFeed').change();
});
</script>

</head>
<body>
	<div class="container-fluid">
		<div class="row">
			<%@include file="layouts/admin.jsp"%>
			<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
				<h1 class="page-header">Add Batch Feed</h1>		
				
				
			
				<form:form commandName="batchFeed" class="form-horizontal">
				<div class="form-group">
						<label for="inputTaskID" class="col-sm-2 control-label">Task ID</label>
						<div class="col-sm-2">
							<form:input name="taskID" path="task.taskId" value="${param.tid}" type="text" class="form-control" id="inputTaskID" readonly="true"/>
						</div>
					</div>	
					<div class="form-group">
						<label for="inputDate" class="col-sm-2 control-label">Date</label>
						<div class="col-sm-3">
							
					
							<div class="container">
							    <div class="row">
							        <div class='col-sm-3'>
							            <div class="form-group">
							                <div class='input-group date' id='datetimepicker1'>
							                    <form:input path="date" type='text' class="form-control" id="inputDate"/>
							                    <span class="input-group-addon">
							                        <span class="glyphicon glyphicon-calendar"></span>
							                    </span>
							                </div>
							            </div>
							        </div>
							        <script type="text/javascript">
							            $(function () {
							                $('#datetimepicker1').datetimepicker({
							                	format: 'YYYY-MM-DD'
							                });
							            });
							        </script>
							    </div>
							</div>
					
						</div>
					</div>	
					
					<div class="form-group">
						<label for="inputBatch" class="col-sm-2 control-label">Distribute Batch ID</label>
						<div class="col-sm-2" >
							<form:input path="supplyBatch.supplyBatchId" type="text" class="form-control" id="inputBatch" value="${param.bid}" readOnly="true" />
						</div>
					</div>	
					
					<div class="form-group">
						<label for="inputBatch" class="col-sm-2 control-label">Bill No</label>
						<div class="col-sm-2">
							<form:input path="billNumber" type="text" class="form-control" id="inputBillNumber"  />
						</div>
					</div>	
					
					<div class="form-group">
						<label for="inputFeed" class="col-sm-2 control-label">Feed</label>
						<div class="col-sm-2">
							<%--  <form:input path="feed.feedId" type="text" class="form-control" id="inputFeed"/>--%>

							<form:select path="feed.feedId" id="inputFeed"	class="form-control">
								<form:options items="${feedReport}" itemLabel="feedNameManufacturer"
									itemValue="feedId" />
							</form:select>
						</div>
					</div>	
					
					<div class="form-group">
						<label for="status" class="col-sm-2 control-label">Status</label>
						<div class="col-sm-2">
							<%--  <form:input path="feed.feedId" type="text" class="form-control" id="inputFeed"/>--%>
							<select name="status"  class="form-control" id="status">
								<option	value="Completed">Completed</option>
								<option value="Incomplete">Incomplete</option>
							</select>
						</div>
					</div>	
					<div class="form-group">
						<label for="inputQuantity" class="col-sm-2 control-label">Quantity</label>
						<div class="col-sm-2">
							<form:input path="quantity" type="text" value="${param.qty}" class="form-control" id="inputQuantity"/>
						</div>
					</div>
					
					<div class="form-group">
						<label for="inputQuantity" class="col-sm-2 control-label">Unit Price</label>
						<div class="col-sm-2">
							<form:input path="unitPrice" type="text" class="form-control" id="inputUnitPrice"/>
						</div>
					</div>
					
					<div class="form-group">
						<label for="inputQuantity" class="col-sm-2 control-label">Amount</label>
						<div class="col-sm-2">
							<form:input path="amount" type="text" class="form-control" id="inputAmount"/>
						</div>
					</div>
					<div class="form-group">
				  		<div class="col-sm-3 control-label">
				  			<input type="submit" value="Add Batch Feed" class="btn btn-primary">	
				  		</div>
				  	</div>			
				</form:form>
				<%@include file="getBatchFeedReport.jsp"%>
			</div>
		</div>
	</div>

	<%@include file="layouts/footer.jsp"%>
</body>
</html>

src/main/webapp/WEB-INF/jsp/addFeed.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>

<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<%@include file="layouts/header.jsp" %>
<title>Add Feed - JP Poultry</title>
</head>
<body>
<div class="container-fluid">
	<div class="row">
		<%@include file="layouts/admin.jsp"%>
		
		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
		
			<h1 class="page-header">Add Feed</h1>
			
			<form:form commandName="feed" class="form-horizontal">
			<form:errors path="*" Class="alert alert-danger" element="div" />
			
				<div class="form-group">
				    <label for="inputName" class="col-sm-2 control-label">Name</label>
				    <div class="col-sm-3">
				      <form:input path="name" type="text" class="form-control" id="inputName" placeholder="Enter Feed Name" />
				    </div>
			  	</div>
			  	
				<div class="form-group">
				    <label for="inputQuantity" class="col-sm-2 control-label">Quantity</label>
				    <div class="col-sm-3">
				      <form:input path="quantity" type="text" class="form-control" id="inputQuantity" placeholder="Enter Quantity" />
				    </div>
			  	</div>	
			  	<div class="form-group">
				    <label for="inputQuantity" class="col-sm-2 control-label">Manufacturer</label>
				    <div class="col-sm-3">
				      <form:input path="manufacturer" type="text" class="form-control" id="inputManufacturer" placeholder="Enter Manufacturer" />
				    </div>
			  	</div>	
			  	
			  	<div class="form-group">
				    <label for="inputQuantity" class="col-sm-2 control-label">Price</label>
				    <div class="col-sm-3">
				      <form:input path="price" type="text" class="form-control" id="inputPrice" placeholder="Enter Manufacturer" />
				    </div>
			  	</div>	
			  	
			  <div class="form-group">
				  <div class="col-sm-4 control-label">
				  	<input type="submit" value="Add Feed" class="btn btn-primary">
				  </div>
			 </div>			  			  	
			
			</form:form>
			
			<h1 class="page-header">Feeds</h1>
		
			<%@include file="getFeedDetails.jsp"%>
		</div>		
	</div>
</div>

	<%@include file="layouts/footer.jsp" %>
</body>
</html>

src/main/webapp/WEB-INF/jsp/addFieldReport.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
	
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<%@include file="layouts/header.jsp" %>

<script type="text/javascript" src="../resources/js/jquery.min.js"></script>
 
<title>Add Field Report - JP Poultry</title>
 <script type="text/javascript">
$(function () {
	
	 var options = {
			 global: {
					useGTM: true
				},
		        chart: {
		            renderTo: 'chart',
		            type: 'line'
		        },
		        title: {
		            text: 'FCR History',
		            x: -20 //center
		        },
		        yAxis: {
		            title: {
		                text: 'FCR'
		            },
		            plotLines: [{
		                value: 0,
		                width: 1,
		                color: '#808080'
		            }]
		        },
		        xAxis: {
		        	 
		                type: 'date',
		                labels: {

		                    },
		                 
		            title: {
		                text: ' '
		            },
		            plotLines: [{
		                value: 0,
		                width: 1,
		                color: '#808080'
		            }]
		        },
		        series: [{tickInterval: 24 * 3600 * 1000}]
		    };
		    
	 		var myParam = location.search.split('bid=')[1]
		    var url =  "./getFieldReport.json?bid="+myParam+"";
		    $.getJSON(url,  function(data) {
		        options.series[0].data = data;
		        var chart = new Highcharts.Chart(options);
		    });
	 
	
	 
});
        </script>
</head>
<body>
 <script src="resources/js/highcharts.js"></script>
 
<script src="resources/js/exporting.js"></script>

<div class="container-fluid">
   
    <div class="row">
        <%@include file="layouts/admin.jsp"%>
        
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            
            <h1 class="page-header">Add Field Report</h1>
            
                <form:form commandName="fieldReport" class="form-horizontal">
                        <div class="form-group">
                            <label for="inputDate" class="col-sm-2 control-label">Date</label>
                            <div class="col-sm-5">
                                
                        
                                <div class="container">
                                    <div class="row">
                                        <div class='col-sm-3'>
                                            <div class="form-group">
                                                <div class='input-group date' id='datetimepicker1'>
                                                    <form:input path="date" type='text' class="form-control" id="inputDate"/>
                                                    <span class="input-group-addon">
                                                        <span class="glyphicon glyphicon-calendar"></span>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                        <script type="text/javascript">
                                            $(function () {$('#datetimepicker1').datetimepicker({
                                                    format: 'YYYY-MM-DD'
                                                });
                                            });
                                        </script>
                                    </div>
                                </div>
                        
                            </div>
                        </div>
                    <div class="form-group">
                        <label for="fieldOfficer" class="col-sm-2 control-label">Field Officer</label>
                        <div class="col-sm-3">
                          <form:select path="fieldOfficer.fieldOfficerId" id="fieldOfficer" class="form-control">
                            <form:options items="${fieldOfficerReport}" itemLabel="fieldOfficerFullName"
                                itemValue="fieldOfficerId" />
                        </form:select>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="inputBatch" class="col-sm-2 control-label">Distribute Batch ID</label>
                        <div class="col-sm-3">
                          <form:input path="supplyBatch.supplyBatchId" value="${param.bid }" type="text" class="form-control" id="inputBatch" readonly="true" />
                        </div>
                    </div>          
                    
                    <div class="form-group">
                        <label for="inputAmountAte" class="col-sm-2 control-label">Amount Ate</label>
                        <div class="col-sm-3">
                          <form:input path="amountAte" type="text" class="form-control" id="inputAmountAte"  />
                        </div>
                    </div>  
                    
                    <div class="form-group">
                        <label for="inputAverageWeight" class="col-sm-2 control-label">Average Weight</label>
                        <div class="col-sm-3">
                          <form:input path="averageWeight" type="text" class="form-control" id="inputAverageWeight"  />
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="inputFCR" class="col-sm-2 control-label">FCR</label>
                        <div class="col-sm-3">
                          <form:input path="FCR" type="text" class="form-control" id="inputFCR"  />
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="inputNumOfChicksDied" class="col-sm-2 control-label">Number Of Chicks Died</label>
                        <div class="col-sm-3">
                          <form:input path="numOfChicksDied" type="text" class="form-control" id="inputNumOfChicksDied"  />
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="inputAge" class="col-sm-2 control-label">Age</label>
                        <div class="col-sm-3">
                          <form:input path="age" type="text" class="form-control" id="inputAge"  />
                        </div>
                    </div>
                    
                     <div class="form-group">
                        <div class="col-sm-4 control-label">
                            <input type="submit" value="Add Field Report" class="btn btn-primary">
                        </div>
                     </div>
                            
                </form:form>
                
             
               <div id="chart" style="min-width: 310px; height: 400px; margin: 0 auto"></div> 
        </div>
        
    </div>
     
</div>


    <%@include file="layouts/footer.jsp" %>
  
</body>
</html>

src/main/webapp/WEB-INF/jsp/addMedicine.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>

<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<%@include file="layouts/header.jsp"%>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Add Medicine - JP Poultry</title>
</head>
<body>
	<div class="container-fluid">
		<div class="row">
			<%@include file="layouts/admin.jsp"%>
			<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
				<h1 class="page-header">Add Medicine</h1>

				<form:form commandName="medicine"  class="form-horizontal">
				<form:errors path="*" Class="alert alert-danger" element="div" />
					<div class="form-group">
						<label for="name" class="col-sm-2 control-label"> Name </label>
						<div class="col-sm-3">
							<form:input path="name" type="text" class="form-control"
								placeholder="Enter Medicine Name" />
						</div>

					</div>
					<div class="form-group">
						<label for="quantity" class="col-sm-2 control-label">Quantity
						</label>
						<div class="col-sm-3">
							<form:input path="quantity" type="text" class="form-control"
								placeholder="Quantity" />
						</div>
					</div>
					<div class="form-group">
						<label for="quantity" class="col-sm-2 control-label">Price
						</label>
						<div class="col-sm-3">
							<form:input path="price" type="text" class="form-control"
								placeholder="price" />
						</div>
					</div>

					<div class="form-group">
						<div class="col-sm-4 control-label">
							<input type="submit" value="Add Medicine" class="btn btn-primary">
						</div>
					</div>


				</form:form>
				<h1 class="page-header">Medicines</h1>
					<%@include file="getMedicineDetails.jsp"%>
			</div>
		</div>
	</div>
	
	<%@include file="layouts/footer.jsp"%>

</body>
</html>

src/main/webapp/WEB-INF/jsp/addMedicineOrderDetails.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>

<%@ taglib  uri="http://www.springframework.org/tags/form" prefix="form"%>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
<%@include file="layouts/admin.jsp" %>
	<form:form commandName="medicineOrderDetails">
		<table>
			<tr>
				<td>Unit Price</td>
				<td><form:input path="unitPrice" /></td>
			</tr>
			<tr>
				<td>Quantity</td>
				<td><form:input path="quantity" /></td>
			</tr>

			<tr>
				<td><input type="submit" value="Add"></td>
			</tr>
		</table>
	</form:form>

</body>
</html>

src/main/webapp/WEB-INF/jsp/getBatchReport.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<%@include file="layouts/header.jsp" %>
<title>Get Purchase Batches</title>
<script type="text/javascript" src="../resources/js/jquery.min.js"></script>
</head>
<body>

<div class="container-fluid">
		<div class="row">
			<%@include file="layouts/admin.jsp"%>

			<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

				<h1 class="page-header">View Purchased Batches</h1>

				<table class="table table-bordered table-hover">
					<thead>
						<tr>
						<th>ID</th>
						<th>Date</th>
						<th>Quantity</th>
						<th>Chick Price</th>
						<th>Purchase Order Value</th>
						<th>Actual Order Value</th>
						<th>Discount</th>
						<th>One Chick Waxing Cost</th>
						<th>Total Waxing Cost</th>
						<th>Supplier</th>
						<th>Payment Request</th>
							 
						</tr>
					</thead>
					<tbody>
					
						<c:forEach items="${batchReport}" var="batch">
						<tr>
							 <td>${batch.batchId}</td>
							 <td>${batch.date}</td>
							  <td>${batch.quantity}</td>
							  <td>${batch.chickPrice}</td>
							  <td>${batch.purchaseOrderValue}</td>
							  <td>${batch.actualOrderValue}</td>
							  <td>${batch.discount}</td>
							  <td>${batch.oneChickWaxingCost}</td>
							  <td>${batch.waxingTotal}</td>
							  <td>${batch.supplier.name}</td>
							  
							  <c:choose>
									<c:when test="${batch.paymentRequest.status == 'Pending'}">
									<security:authorize ifAnyGranted="ROLE_ADMIN">
										  <c:url var="paymentRequest" value="approvePaymentRequest.html?pid=${batch.paymentRequest.paymentId}">Payment Request</c:url>
							 				 <td><a href="${paymentRequest}">${batch.paymentRequest.paymentId}</a></td>
											</security:authorize>
									</c:when>
									<c:when test="${batch.approved == false}">
									<security:authorize ifAnyGranted="ROLE_ADMIN">
										  <c:url var="approveBatch" value="approveBatch.html?bid=${batch.batchId}">Approve Batch</c:url>
							 				 <td><a href="${approveBatch}">Approve Batch</a></td>
											</security:authorize>
									</c:when>

								</c:choose>
							  
							 
							  </tr>
						</c:forEach>
						
					</tbody>
				</table>
			</div>

		</div>
	</div>

	<%@include file="layouts/footer.jsp" %>

</body>
</html>

src/main/webapp/WEB-INF/jsp/index.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<c:redirect url="/login.html"/>